<?php

declare(strict_types=1);

use Hyperf\Database\Migrations\Migration;
use Hyperf\Database\Schema\Blueprint;
use Hyperf\Database\Schema\Schema;
use Hyperf\DbConnection\Db;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('_account', static function (Blueprint $table) {
            $table->bigInteger('id')->primary();
            $table->smallInteger('game_id');
            $table->string('funpay_name');
            $table->string('ingame_id')->nullable();
            $table->string('ingame_name')->nullable();
            $table->string('ingame_corp')->nullable();
            $table->string('ingame_alliance')->nullable();
            $table->boolean('is_seller')->default(false);
            $table->string('discord')->nullable();
            $table->timestamp('updated_at')->useCurrent();
            $table->unique(['game_id', 'ingame_id']);
        });

        Db::statement('ALTER TABLE _account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
};
